### ISSUE TITLE
Implement a button variant

### ISSUE THREAD

**Issue by vronskyvitaly** [vronskyvitaly/next-start#25]
[https://www.figma.com/file/pWMYiKvyLDshafNSgYu5Z5/Shop?type=design&node-id=405-3698&mode=design&t=SfYL7Ve1oT8WoHUL-4](url)

**Comment by vronskyvitaly** [comment]
You also need to add an option to the story

**Comment by fedjes** [comment]
Button

**Comment by vronskyvitaly** [comment]
https://www.figma.com/file/pWMYiKvyLDshafNSgYu5Z5/Shop?type=design&node-id=405-3698&mode=design&t=NGaYb4gTKNEbFak5-4
