### ISSUE TITLE
component/header

### ISSUE THREAD

**Issue by vronskyvitaly** [vronskyvitaly/next-start#45]
[Link figma](https://www.figma.com/file/pWMYiKvyLDshafNSgYu5Z5/Shop?type=design&node-id=616-22796&mode=design&t=kmIGDr7id9y9rxip-4)

![Image](https://github.com/vronskyvitaly/next-start/assets/94834175/609c9f14-6d79-4c5f-8a2d-24fa3a7c2e73)

**Comment by fedjes** [comment]
_header -old version
